### ISSUE TITLE
Great gem, why not 1.0? :)

### ISSUE THREAD

**Issue by paneq** [Envek/after_commit_everywhere#11]
Hey :) 

I am the author of https://blog.arkency.com/2015/10/run-it-in-background-job-after-commit/ . **Thank you** for writing this gem, I believe it just works. What's stopping us from releasing version 1.0 😃  ?

Based on: https://rubygems.org/gems/after_commit_everywhere/versions/0.1.5

```
TOTAL DOWNLOADS: 727,852
FOR THIS VERSION: 152,072
```

and 0 open issues reported here.

**Comment by Envek** [comment]
Well, I was waiting for feedback for it to either improve or change something, but seems that everyone likes it as it is, so probably we really can just bump version and manifest that it is stable (as it is) :smile:

**Comment by Envek** [comment]
Released [v1.0.0](https://github.com/Envek/after_commit_everywhere/releases/tag/v1.0.0).

Thanks for paying attention to this!
