### ISSUE TITLE
Braking tests

### ISSUE THREAD

**Issue by axos88** [Envek/after_commit_everywhere#2]
Hello!

Is there a way to configure thig gem to ignore transactions when in tests? 
Our DatabaseCleaner is set up to use rollbacks, so obviously the transactions are not committed before the expectations, and the tests fail.

The README.md sais it's working with DBCleaner, but can you include a few lines on how to set it up?

Thanks,

**Comment by axos88** [comment]
NVM

**Comment by Envek** [comment]
No configuration required, gem itself will determine if it is running inside of “test transaction”: https://github.com/Envek/after_commit_everywhere/blob/57ad6aa1658fdf3dd4f638955af09d653e0afdbb/lib/after_commit_everywhere.rb#L93-L94

Could you please share what and why didn't work with your test suite so other users could find and fix too?

**Comment by axos88** [comment]
It was simply a typo, so unrelated to this gem. Yey dynamic languages :|
